### ISSUE TITLE
Is it possible to split columns into multiple cells?

### ISSUE THREAD

**Issue by ChenMatsu** [LuisEnMarroquin/json-as-xlsx#45]
I would like to generate xlsx file with columns like below: 

<img width="1512" alt="スクリーンショット 2022-06-13 11 43 49" src="https://user-images.githubusercontent.com/48172540/173275645-040db9d1-8172-4d09-ab62-0973d6b88b0f.png">

Is it possible to split the columns just by define columns like below:
```
const logColumns = [
        { label: "Date", value: "Date" },
        {
          labels: [
            { label: "Hour"},
            { label: "Min" },
          ],
          value: "Time",
          direction: "vertical",
        }
      ];
```

Currently the columns with array will return undefined, is there any option or workaround to define this kind of sheet in this situation?

**Comment by elyse0** [comment]
No, it's not currently supported

> Is it possible to split the columns just by define columns like below:

In my opinion, this is more like **merging the columns** instead of splitting them 🤔 

Looking at your layout, I think this package can't help you much since there's no support for horizontal layouts nor cell merging

Having said that, you could try modifying the workbook yourself using a callback

```js
let callback = function (workbook) {
   // Column merging logic using SheetJs functions
}

xlsx(data, settings, callback)
```

Some examples of this are:
- https://github.com/SheetJS/sheetjs/issues/416
- https://github.com/SheetJS/sheetjs/issues/2128

In the end, maybe for your specific case you will be better off using [SheetJs](https://github.com/SheetJS/sheetjs) directly

**Comment by ChenMatsu** [comment]
Sorry for late reply and thank you for your response. Yes, I would like to merge columns as the image shows, and I will try to explore SheetJS to see any workaround, thanks!
