### ISSUE TITLE
Can I add next Row?

### ISSUE THREAD

**Issue by DRBofa** [LuisEnMarroquin/json-as-xlsx#69]
Please ! help me
I want to merge cell like this picture It's can be or not?
I want to add next row and sum of any number?

<img width="308" alt="image" src="https://user-images.githubusercontent.com/35457763/218651560-a6facb19-09ad-4a98-84a7-77c3c038eb89.png">

**Comment by LuisEnMarroquin** [comment]
Hi, currently cell merge is not supported because the purpose of this library is to convert a JSON format to XLSX and the JSONs do not have merged columns :c 

An alternative is that you can put the name of the company in both the file name and the sheet name

You can also programmatically process the information you want, but take into account that if you add a column with a sum of values when exported as an XLSX file it will only be a numerical value not linked to the cells where you created it from

```ts
import xlsx from "json-as-xlsx";

function generateColumns(accumulator: any, element: any) {
  const keys = Object.keys(element);
  keys.forEach((key) => !accumulator.includes(key) && accumulator.push(key));
  return accumulator;
}

const oldData = [
  { January: 100, February: 200, March: 300 },
  { January: 150, February: 250, March: 350 },
];

const newData = oldData.map((item) => {
  const newItem = {
    ...item,
    TOTAL: item.January + item.February + item.March,
  };
  return newItem;
});

const keys = newData.reduce(generateColumns, []);
const columns = keys.map((key: any) => ({ label: key, value: key }));

xlsx([{ sheet: "CompanyName", columns: columns, content: newData }], {
  fileName: "CompanyName",
  extraLength: 5,
});
```

<img width="652" alt="image" src="https://user-images.githubusercontent.com/35376824/224578668-775fadce-bfe1-4e0f-ac90-215b17aabe85.png">
