### ISSUE TITLE
styling to cells/ header

### ISSUE THREAD

**Issue by s-kris** [LuisEnMarroquin/json-as-xlsx#7]
Can you add styling via a style object? 
ref: https://github.com/protobi/js-xlsx

**Comment by LuisEnMarroquin** [comment]
Hi, I did not implement it before because I thought it would be hard

Now the full options from sheetjs are available in `v1.1.7`, just add the styles in the 3rd argument as `writeOptions`

![image](https://user-images.githubusercontent.com/35376824/95666987-4be61f00-0b25-11eb-8563-4a1cdf35b098.png)

Here is the official documentation: https://github.com/SheetJS/sheetjs#writing-options
